### ISSUE TITLE
List URL exceptions.

### ISSUE THREAD

**Issue by Glossow** [nitmir/irc-url-bot#1]
How to make a blacklist of URL/domains?

**Comment by nitmir** [comment]
Url from IRC messages are match here:

https://github.com/nitmir/irc-url-bot/blob/dfbfed8168e740c97107d893caeb2df76ac9607a/urlbot.py#L169

You cloud add something like:
`if url not in {'http://bad_url1', 'http://bad_url2'}:`
or something like:
`if not any(re.match(pattern, url) for pattern in [pattern1, pattern2, pattern3, …]):`

pull requests are welcome

**Comment by Glossow** [comment]
Unfortunately, I am not know a python. And why I get: `SyntaxError: invalid syntax`. Are you can update urlbot.py?

> pull requests are welcome

Not sure how I can do it. https://i.imgur.com/MWwJKVV.png

**Comment by nitmir** [comment]
I add a 'blacklist'  parameter which is a list or regular expression. If a URL match any of the blacklist regular expressions, it is ignored.

**Comment by Glossow** [comment]
Thank you.
