### ISSUE TITLE
Information about the picture.

### ISSUE THREAD

**Issue by Glossow** [nitmir/irc-url-bot#4]
Hello.
Not sure whether this is possible, but maybe there is a way to show information about the pictures.
For example:

> user: https://i.imgur.com/test.png
> urlbot: Type: image :: Format: png :: Dimensions: 1366x768 px. :: Size: 1.21 MB

**Comment by nitmir** [comment]
I had a 'fallback_notitle' settings which is True by default. Then the link do not point to an html, type, format and size are returned.

**Comment by Glossow** [comment]
At the moment i don't have other requests. Thank you so much, **nitmir**.
