### ISSUE TITLE
Twitter: French language

### ISSUE THREAD

**Issue by dom6770** [nitmir/irc-url-bot#5]
Hey,

I noticed that the url-bot responds twitter-related content in french. 

`<@AbGedreht> https://twitter.com`
`<Bot> Twitter. Ce qu'il se passe.`

and f.ex.

`<@AbGedreht> https://twitter.com/markhoppus/status/868498943298027520`
`<Bot> Mark Hoppus sur Twitter : "Fine. I'll play. https://t.co/bUTYw5txDo"`

is there a way to change it to english?

**Comment by nitmir** [comment]
Strangely, then no prefered language is send by the http client, twitter respond in french. I'll add an option to allow users to specify custom headers to send then fetching url. In particular, setting the Accept-Language header should do the tricks.
